name: Maptime AMS
baseurl: /maptimeAMS

animation-interval: 7500
building-stroke-width: 8

venue: Waag Society, Nieuwmarkt 4
venue-url: "https://www.openstreetmap.org/#map=19/52.37268/4.90042"

next-event: November 19th
next-event-url: http://www.meetup.com/Maptime-AMS/events/213796602/

links:
  - title: Maptime HQ
    url: http://maptime.io/

  - title: Meetup
    url: http://www.meetup.com/Maptime-AMS

  - title: Twitter
    url: https://twitter.com/MaptimeAMS

  - title: Waag Society
    url: http://waag.org/

  - title: GitHub
    url: https://github.com/waagsociety/maptimeAMS

  - title: Resources
    url: https://github.com/waagsociety/maptimeAMS/tree/gh-pages/resources